#!/usr/bin/env zsh
brew bundle
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,zsh,git,kitty,yabai,claude"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
